site_name: simpleRM docs

pages:
  - 'index.md'
  - 'requirements.md'

extra_css:
    - css/extra.css
    - css/font_awesome/css/font-awesome.min.css

markdown_extensions:
    - toc:
        permalink: ïƒ
    - admonition: